groups:
  - name: example-alerts
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 0.01
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "Instance {{ $labels.instance }} is using high CPU"
