version: '3.8'

services:
  alertmanager:
    image: registry.redhat.io/openshift4/ose-prometheus-alertmanager:v4.10.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    restart: unless-stopped
    networks:
      - monitoring
  prometheus:
    image: registry.redhat.io/openshift4/ose-prometheus:v4.10.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - ./data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
